-- MySQL Script generated by MySQL Workbench
-- jue 01 jul 2021 12:20:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GRN
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GRN` ;

-- -----------------------------------------------------
-- Schema GRN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GRN` ;
USE `GRN` ;

-- -----------------------------------------------------
-- Table `GRN`.`strain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRN`.`strain` ;

CREATE TABLE IF NOT EXISTS `GRN`.`strain` (
  `strain_id` INT NOT NULL AUTO_INCREMENT,
  `strain_name` VARCHAR(200) NULL,
  `refseq_ftp` VARCHAR(300) NULL,
  `genbank_ftp` VARCHAR(300) NULL,
  `assembly` VARCHAR(45) NULL,
  PRIMARY KEY (`strain_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRN`.`organism`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRN`.`organism` ;

CREATE TABLE IF NOT EXISTS `GRN`.`organism` (
  `organism_id` INT NOT NULL AUTO_INCREMENT,
  `organism_name` VARCHAR(200) NOT NULL,
  `strain_id` INT NOT NULL,
  PRIMARY KEY (`organism_id`),
  INDEX `fk_organism_strain1_idx` (`strain_id` ASC) VISIBLE,
  CONSTRAINT `fk_organism_strain1`
    FOREIGN KEY (`strain_id`)
    REFERENCES `GRN`.`strain` (`strain_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRN`.`gene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRN`.`gene` ;

CREATE TABLE IF NOT EXISTS `GRN`.`gene` (
  `gene_id` INT NOT NULL AUTO_INCREMENT,
  `original_gene_id` VARCHAR(45) NOT NULL,
  `gene_name` VARCHAR(45) NULL,
  `protein_id` VARCHAR(45) NULL,
  `coord_init` INT NOT NULL,
  `coord_end` INT NOT NULL,
  `strand` VARCHAR(45) NOT NULL,
  `organism_id` INT NOT NULL,
  PRIMARY KEY (`gene_id`),
  INDEX `fk_Gen_organism_idx` (`organism_id` ASC) VISIBLE,
  CONSTRAINT `fk_Gen_organism`
    FOREIGN KEY (`organism_id`)
    REFERENCES `GRN`.`organism` (`organism_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRN`.`edge_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRN`.`edge_type` ;

CREATE TABLE IF NOT EXISTS `GRN`.`edge_type` (
  `edge_type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`edge_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRN`.`edge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRN`.`edge` ;

CREATE TABLE IF NOT EXISTS `GRN`.`edge` (
  `gene_id1` INT NOT NULL,
  `gene_id2` INT NOT NULL,
  `edge_type_id` INT NOT NULL,
  `target_strand` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`gene_id1`, `gene_id2`),
  INDEX `fk_Gen_has_Gen_Gen2_idx` (`gene_id2` ASC) VISIBLE,
  INDEX `fk_Gen_has_Gen_Gen1_idx` (`gene_id1` ASC) VISIBLE,
  INDEX `fk_edge_table11_idx` (`edge_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Gen_has_Gen_Gen1`
    FOREIGN KEY (`gene_id1`)
    REFERENCES `GRN`.`gene` (`gene_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Gen_has_Gen_Gen2`
    FOREIGN KEY (`gene_id2`)
    REFERENCES `GRN`.`gene` (`gene_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_edge_table11`
    FOREIGN KEY (`edge_type_id`)
    REFERENCES `GRN`.`edge_type` (`edge_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GRN`.`ortholog_edge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRN`.`ortholog_edge` ;

CREATE TABLE IF NOT EXISTS `GRN`.`ortholog_edge` (
  `edge_gene_id1` INT NOT NULL,
  `edge_gene_id2` INT NOT NULL,
  `organism_derived_id` INT NOT NULL,
  PRIMARY KEY (`edge_gene_id1`, `edge_gene_id2`, `organism_derived_id`),
  INDEX `fk_edge_has_organism_organism1_idx` (`organism_derived_id` ASC) VISIBLE,
  CONSTRAINT `fk_edge_has_organism_edge1`
    FOREIGN KEY (`edge_gene_id1` , `edge_gene_id2`)
    REFERENCES `GRN`.`edge` (`gene_id1` , `gene_id2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_edge_has_organism_organism1`
    FOREIGN KEY (`organism_derived_id`)
    REFERENCES `GRN`.`organism` (`organism_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
